"""raplce miliseconds in subscriber.created_at 

Revision ID: 5a98cddbb603
Revises: 73f8e9667f2e
Create Date: 2025-03-14 01:14:39.320824

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5a98cddbb603'
down_revision = '73f8e9667f2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
